# Setup
setup: selflabel

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10

# Augmentations
augmentation_strategy: cutout 
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
   num_strong_augs: 8
   cutout_kwargs:
     n_holes: 2
     length: 16
     random: True
transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Model
backbone: resnet18
finetune_backbone: True

# optimizer
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001

scheduler: constant

# Loss
criterion: selflabel
criterion_kwargs:
   confidenceCE:
      threshold: 0.9
      threshold_max: 0.9
      apply_class_balancing: True

# Hyperparameters
batch_size: 1024
epochs: 200
eval_interval: 20
num_workers: 8
tau: 1.0
topk: 1000
encode_length: 64

# Path
cghash_subdir: cifar-cghash-l64
cghash_checkpoint: checkpoint.pth.tar
cghash_model: model.pth.tar

selflabel_subdir: cifar-selflabel-l64
selflabel_checkpoint: checkpoint.pth.tar
selflabel_model: model.pth.tar
