# Setup
setup: simclr

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10

# transformation
transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Model
backbone: resnet18
model_kwargs:
   head: mlp
   features_dim: 128
finetune_backbone: False


# Hyperparameters
batch_size: 512 
num_workers: 8
topk: 20
use_identity_head: False
output_dim: 128
temperature: 0.1
pretrained_path: ./models/pretrained_backbones/simclr_cifar-10_300ep.pth.tar